version: '3.8'

services:
  podcast-app:
    container_name: podcast-app
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5000:5000"
      - "5173:5173"
    volumes:
      - ../:/app
      - /app/node_modules
      - ../public/audio:/app/public/audio  
      - ../output:/app/output  
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=5000
      # Use dynamic API URL based on platform
      - VITE_API_URL=${DOCKER_GATEWAY_HOST:-http://localhost:5000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - podcast-network
    # Add extra hosts for WSL2 compatibility
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  podcast-network:
    name: podcast-network-${COMPOSE_PROJECT_NAME:-default}
    driver: bridge